### ISSUE TITLE
Rebuild Grid/Timing System

### ISSUE THREAD

**Issue by JohannesKlauss** [JohannesKlauss/splinter.io#316]
Currently we have multiple system to measure time:

* Seconds
* Bars
* Beats
* Pixels

We need a single source of truth and that would be seconds, since this is the measure that the ToneJS Transport uses. So everything else should be derived from seconds.
This will also allow us to create multiple BPMs and Time Signatures, because they will all depend on seconds.

Since this is a crucial feature to move on to a more professional workflow this should be priority. Also there are a lot of UI things depending on this and right now it's not very stable. So let's get this out of the way to not only be way more cooler than bandlab but to also have a stable system that everything else can build upon.

Building this up includes:
- [x] Setting the base resolution to 64th #312
- [x] Multiple BPM and tempo changes #106 
- [x] Fixing up the ruler bar items #308 
- [x] Connect bpm changes to Tone Transport #314
- [ ] Rebuilding the zoom levels #311 
- [x] Showing bars and beats in time information #313
- [x] Display info in its own panel #315

**Comment by JohannesKlauss** [comment]
As stated in #395 we should use interpolation and mathematical functions to express bpm changes over time.
I guess we could also do that with time signatures.

The current way is very bloated and not very performant and has a lot of problems. So we need to reimplement this whole thing.

I guess it is also smarter to have frames as a source of truth and not seconds. Because the sample rate actually provides the smallest possible division, which currently is just 44100, but could change with web audio api v2 I guess. So let's build it up generically.

**Comment by JohannesKlauss** [comment]
Since we are using superpowered for waveform analysis now, we should focus on finishing the grid/timing system and finish the waveform stuff at the end, when we are implementing superpowered anyways.
